// Generated by dts-bundle v0.5.0

declare module 'TJAngular' {
    export function Spec(classname?: string): (target: any) => void;
    export function XSpec(classname?: string): (target: any) => void;
    export function FSpec(classname?: string): (target: any) => void;
    export function Mocks(mocks: any): (target: any, propertyKey: string) => void;
    export function Inject(providerName: string, moduleName: string, dependencies?: Array<string>): (target: any, propertyKey: string) => void;
    export function InjectMock(providerName: string): (target: any, propertyKey: string) => void;
    export function Test(name?: string): (target: any, propertyKey: string) => void;
    export function XTest(name?: string): (target: any, propertyKey: string) => void;
    export function FTest(name?: string): (target: any, propertyKey: string) => void;
    export function Before(): (target: any, propertyKey: string) => void;
    export function ProvideMock(providerName: string, providerType: string): (target: any) => void;
    export function ProvideMockService(providerName: string): (target: any) => void;
    export function ProvideMockProvider(providerName: string): (target: any) => void;
    export function ProvideMockController(providerName: string): (target: any) => void;
    export function ProvideMockDirective(providerName: string): (target: any) => void;
    export function ProvideMockValue(providerName: string): (target: any) => void;
    export function ProvideMockConstant(providerName: string): (target: any) => void;
}

